//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9179
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9179.
// 
namespace Estore.Ce.ProductService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IProductSoapService_soap", Namespace="http://tempuri.org/")]
    public partial class IProductSoapService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public IProductSoapService() {
            this.Url = "http://192.168.254.171:8081/ProductService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IProductSoapService/GetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ProductDto[] GetAll(bool isActive) {
            object[] results = this.Invoke("GetAll", new object[] {
                        isActive});
            return ((ProductDto[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAll(bool isActive, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAll", new object[] {
                        isActive}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProductDto[] EndGetAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProductDto[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IProductSoapService/GetPaged", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ProductDto[] GetPaged(bool isActive, int pageNumber, int pageSize) {
            object[] results = this.Invoke("GetPaged", new object[] {
                        isActive,
                        pageNumber,
                        pageSize});
            return ((ProductDto[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPaged(bool isActive, int pageNumber, int pageSize, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPaged", new object[] {
                        isActive,
                        pageNumber,
                        pageSize}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProductDto[] EndGetPaged(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProductDto[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IProductSoapService/GetRecordCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetRecordCount(bool isActive) {
            object[] results = this.Invoke("GetRecordCount", new object[] {
                        isActive});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRecordCount(bool isActive, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRecordCount", new object[] {
                        isActive}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndGetRecordCount(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductDto {
        
        private string barcodeField;
        
        private string brandField;
        
        private string categoryField;
        
        private bool isActiveField;
        
        private int packingSizeField;
        
        private string packingUnitField;
        
        private int productIdField;
        
        private System.Nullable<int> productParentIdField;
        
        private string productImageUrlField;
        
        private string productNameField;
        
        private System.Nullable<decimal> sellingPriceField;
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public int PackingSize {
            get {
                return this.packingSizeField;
            }
            set {
                this.packingSizeField = value;
            }
        }
        
        /// <remarks/>
        public string PackingUnit {
            get {
                return this.packingUnitField;
            }
            set {
                this.packingUnitField = value;
            }
        }
        
        /// <remarks/>
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ProductParentId {
            get {
                return this.productParentIdField;
            }
            set {
                this.productParentIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProductImageUrl {
            get {
                return this.productImageUrlField;
            }
            set {
                this.productImageUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SellingPrice {
            get {
                return this.sellingPriceField;
            }
            set {
                this.sellingPriceField = value;
            }
        }
    }
}
