//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9179
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9179.
// 
namespace Estore.Ce.PreStockCountService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IPreStockCountService_soap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseTransactionDto))]
    public partial class IPreStockCountService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public IPreStockCountService() {
            this.Url = "http://192.168.89.1:8081/PreStockCountService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPreStockCountService/Post", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreatePreStockCountCommandResponse Post([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] CreatePreStockCountCommandDto[] preStockCountsDto) {
            object[] results = this.Invoke("Post", new object[] {
                        preStockCountsDto});
            return ((CreatePreStockCountCommandResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPost(CreatePreStockCountCommandDto[] preStockCountsDto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Post", new object[] {
                        preStockCountsDto}, callback, asyncState);
        }
        
        /// <remarks/>
        public CreatePreStockCountCommandResponse EndPost(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CreatePreStockCountCommandResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePreStockCountCommandDto : BaseTransactionDto {
        
        private string barcodeField;
        
        private string deviceIdField;
        
        private int locationIdField;
        
        private System.DateTime scanDateField;
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public int LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ScanDate {
            get {
                return this.scanDateField;
            }
            set {
                this.scanDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreatePreStockCountCommandDto))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseTransactionDto {
        
        private int lineNumberField;
        
        private int packingSizeField;
        
        private int packingUnitIdField;
        
        private int productIdField;
        
        private int quantityField;
        
        /// <remarks/>
        public int LineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        public int PackingSize {
            get {
                return this.packingSizeField;
            }
            set {
                this.packingSizeField = value;
            }
        }
        
        /// <remarks/>
        public int PackingUnitId {
            get {
                return this.packingUnitIdField;
            }
            set {
                this.packingUnitIdField = value;
            }
        }
        
        /// <remarks/>
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePreStockCountCommandResponse {
        
        private bool successField;
        
        private string messageField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
}
