//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9179
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9179.
// 
namespace Estore.Ce.LocationService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ILocationSoapService_soap", Namespace="http://tempuri.org/")]
    public partial class ILocationSoapService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ILocationSoapService() {
            this.Url = "http://192.168.1.112:8090/LocationService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ILocationSoapService/Locations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public LocationDto[] Locations(bool isActive) {
            object[] results = this.Invoke("Locations", new object[] {
                        isActive});
            return ((LocationDto[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLocations(bool isActive, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Locations", new object[] {
                        isActive}, callback, asyncState);
        }
        
        /// <remarks/>
        public LocationDto[] EndLocations(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((LocationDto[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LocationDto {
        
        private int locationIdField;
        
        private bool isActiveField;
        
        private bool isBadOrderField;
        
        private bool isSellingAreaField;
        
        private bool isWarehouseField;
        
        private string locationNameField;
        
        /// <remarks/>
        public int LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public bool IsBadOrder {
            get {
                return this.isBadOrderField;
            }
            set {
                this.isBadOrderField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSellingArea {
            get {
                return this.isSellingAreaField;
            }
            set {
                this.isSellingAreaField = value;
            }
        }
        
        /// <remarks/>
        public bool IsWarehouse {
            get {
                return this.isWarehouseField;
            }
            set {
                this.isWarehouseField = value;
            }
        }
        
        /// <remarks/>
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
    }
}
