//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9179
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9179.
// 
namespace Estore.Ce.PreStockReceiptService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IPreStockReceiptSoapService_soap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasePreTransactionCreateDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasePreTransactionGetDto))]
    public partial class IPreStockReceiptSoapService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public IPreStockReceiptSoapService() {
            this.Url = "http://192.168.31.93:8090/PreStockReceiptService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPreStockReceiptSoapService/GetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public GetAllPreStockReceiptQueryRequestDto[] GetAll() {
            object[] results = this.Invoke("GetAll", new object[0]);
            return ((GetAllPreStockReceiptQueryRequestDto[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAll(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAll", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public GetAllPreStockReceiptQueryRequestDto[] EndGetAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetAllPreStockReceiptQueryRequestDto[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPreStockReceiptSoapService/Post", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApiResponse Post([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] CreatePreStockReceiptCommandRequestDto[] preStockReceiptsDto) {
            object[] results = this.Invoke("Post", new object[] {
                        preStockReceiptsDto});
            return ((ApiResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPost(CreatePreStockReceiptCommandRequestDto[] preStockReceiptsDto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Post", new object[] {
                        preStockReceiptsDto}, callback, asyncState);
        }
        
        /// <remarks/>
        public ApiResponse EndPost(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ApiResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPreStockReceiptQueryRequestDto : BasePreTransactionGetDto {
        
        private int idField;
        
        private System.Nullable<int> purchaseOrderNumberField;
        
        private int quantityOnOrderField;
        
        private string supplierInvoiceNumberField;
        
        private string supplierNameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PurchaseOrderNumber {
            get {
                return this.purchaseOrderNumberField;
            }
            set {
                this.purchaseOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        public int QuantityOnOrder {
            get {
                return this.quantityOnOrderField;
            }
            set {
                this.quantityOnOrderField = value;
            }
        }
        
        /// <remarks/>
        public string SupplierInvoiceNumber {
            get {
                return this.supplierInvoiceNumberField;
            }
            set {
                this.supplierInvoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SupplierName {
            get {
                return this.supplierNameField;
            }
            set {
                this.supplierNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetAllPreStockReceiptQueryRequestDto))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BasePreTransactionGetDto {
        
        private bool isForPostingField;
        
        private string barcodeField;
        
        private string deviceIdField;
        
        private int lineNumberField;
        
        private string packingUnitField;
        
        private int productIdField;
        
        private string productNameField;
        
        private int quantityField;
        
        private System.Nullable<System.DateTime> scanDateField;
        
        /// <remarks/>
        public bool IsForPosting {
            get {
                return this.isForPostingField;
            }
            set {
                this.isForPostingField = value;
            }
        }
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public int LineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PackingUnit {
            get {
                return this.packingUnitField;
            }
            set {
                this.packingUnitField = value;
            }
        }
        
        /// <remarks/>
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ScanDate {
            get {
                return this.scanDateField;
            }
            set {
                this.scanDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApiResponse {
        
        private bool isSuccessField;
        
        private string messageField;
        
        /// <remarks/>
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreatePreStockReceiptCommandRequestDto))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BasePreTransactionCreateDto {
        
        private bool isForPostingField;
        
        private string barcodeField;
        
        private string deviceIdField;
        
        private int productIdField;
        
        private int quantityField;
        
        private System.Nullable<System.DateTime> scanDateField;
        
        /// <remarks/>
        public bool IsForPosting {
            get {
                return this.isForPostingField;
            }
            set {
                this.isForPostingField = value;
            }
        }
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string DeviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ScanDate {
            get {
                return this.scanDateField;
            }
            set {
                this.scanDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePreStockReceiptCommandRequestDto : BasePreTransactionCreateDto {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
}
